<?php
require_once __DIR__ . '/../LAMP.php';

/**
 * @OA\Schema(
 *   type="string",
 *   enum={"tap", "page", "notification", "error"},
 *   description="The kind of interaction the metadata event contains."
 * )
 */
abstract class MetadataEventType extends LAMP {
    const Tap = "tap";
    const Page = "page";
    const Notification = "notification";
    const Error = "error";
}

/**
 * @OA\Schema(
 *   description="An event generated by a participant interacting with the LAMP app."
 * )
 */
class MetadataEvent extends LAMP {
    use TypeDriver;

    /**
     * @OA\Property(
     *   ref="#/components/schemas/Identifier",
     *   x={"type"="#/components/schemas/MetadataEvent"},
     *   description="The self-referencing identifier to this object."
     * )
     */
    public $id = null;

    /** 
     * @OA\Property(
     *   ref="#/components/schemas/Attachments",
     *   description="External or out-of-line objects attached to this object."
     * )
     */
    public $attachments = null;

    /** 
     * @OA\Property(
     *   ref="#/components/schemas/MetadataEventType",
     *   description="The type of the metadata event."
     * )
     */
    public $type = null; 

    /** 
     * @OA\Property(
     *   ref="#/components/schemas/Timestamp",
     *   description="The date and time when this event was recorded."
     * )
     */
    public $timestamp = null;

    /** 
     * @OA\Property(
     *   type="string",
     *   description="The item information recorded within the metadata event."
     * )
     */
    public $item = null;

    /** 
     * @OA\Get(
     *   path="/metadata_event/{metadata_event_id}",
     *   operationId="MetadataEvent::view",
     *   tags={"MetadataEvent"},
     *   x={"owner"={
     *     "$ref"="#/components/schemas/MetadataEvent"}
     *   },
     *   summary="Get a single metadata event, by identifier.",
     *   description="Get a single metadata event, by identifier.",
     *   @OA\Parameter(
     *     name="metadata_event_id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(
     *       ref="#/components/schemas/Identifier",
     *       x={"type"={
     *         "$ref"="#/components/schemas/MetadataEvent"}
     *       },
     *     )
     *   ),
     *   @OA\Response(response=200, ref="#/components/responses/Success"),
     *   @OA\Response(response=403, ref="#/components/responses/Forbidden"),
     *   @OA\Response(response=404, ref="#/components/responses/NotFound"),
     *   @OA\Response(response=500, ref="#/components/responses/ServerFault"),
     *   security={{"Authorization": {}}},
     * )
     */
    public static function view($metadata_event_id) {
        self::authorize(function($type, $value) {
            return false; // TODO
        });
        return null;
    }

    /** 
     * @OA\Get(
     *   path="/participant/{participant_id}/metadata_event",
     *   operationId="MetadataEvent::all_by_participant",
     *   tags={"MetadataEvent"},
     *   x={"owner"={
     *     "$ref"="#/components/schemas/MetadataEvent"}
     *   },
     *   summary="Get the set of all metadata events produced by a participant, by identifier.",
     *   description="Get the set of all metadata events produced by a participant, by identifier.",
     *   @OA\Parameter(
     *     name="participant_id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(
     *       ref="#/components/schemas/Identifier",
     *       x={"type"={
     *         "$ref"="#/components/schemas/Participant"}
     *       },
     *     )
     *   ),
     *   @OA\Response(response=200, ref="#/components/responses/Success"),
     *   @OA\Response(response=403, ref="#/components/responses/Forbidden"),
     *   @OA\Response(response=404, ref="#/components/responses/NotFound"),
     *   @OA\Response(response=500, ref="#/components/responses/ServerFault"),
     *   security={{"Authorization": {}}},
     * )
     */
    public static function all_by_participant($participant_id) {
        self::authorize(function($type, $value) use($participant_id) {
            return false; // TODO
        });
        return null;
    }

    /** 
     * @OA\Get(
     *   path="/study/{study_id}/metadata_event",
     *   operationId="MetadataEvent::all_by_study",
     *   tags={"MetadataEvent"},
     *   x={"owner"={
     *     "$ref"="#/components/schemas/MetadataEvent"}
     *   },
     *   summary="Get the set of all metadata events produced by participants enrolled in a study, by identifier.",
     *   description="Get the set of all metadata events produced by participants enrolled in a study, by identifier.",
     *   @OA\Parameter(
     *     name="study_id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(
     *       ref="#/components/schemas/Identifier",
     *       x={"type"={
     *         "$ref"="#/components/schemas/Study"}
     *       },
     *     )
     *   ),
     *   @OA\Response(response=200, ref="#/components/responses/Success"),
     *   @OA\Response(response=403, ref="#/components/responses/Forbidden"),
     *   @OA\Response(response=404, ref="#/components/responses/NotFound"),
     *   @OA\Response(response=500, ref="#/components/responses/ServerFault"),
     *   security={{"Authorization": {}}},
     * )
     */
    public static function all_by_study($study_id) {
        return MetadataEvent::all_by_researcher($study_id);
    }

    /** 
     * @OA\Get(
     *   path="/researcher/{researcher_id}/metadata_event",
     *   operationId="MetadataEvent::all_by_researcher",
     *   tags={"MetadataEvent"},
     *   x={"owner"={
     *     "$ref"="#/components/schemas/MetadataEvent"}
     *   },
     *   summary="Get the set of all metadata events produced by participants enrolled in any study conducted by a researcher, by identifier.",
     *   description="Get the set of all metadata events produced by participants enrolled in any study conducted by a researcher, by identifier.",
     *   @OA\Parameter(
     *     name="researcher_id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(
     *       ref="#/components/schemas/Identifier",
     *       x={"type"={
     *         "$ref"="#/components/schemas/Researcher"}
     *       },
     *     )
     *   ),
     *   @OA\Response(response=200, ref="#/components/responses/Success"),
     *   @OA\Response(response=403, ref="#/components/responses/Forbidden"),
     *   @OA\Response(response=404, ref="#/components/responses/NotFound"),
     *   @OA\Response(response=500, ref="#/components/responses/ServerFault"),
     *   security={{"Authorization": {}}},
     * )
     */
    public static function all_by_researcher($researcher_id) {
        self::authorize(function($type, $value) {
            return false; // TODO
        });
        return null;
    }

    /** 
     * @OA\Get(
     *   path="/metadata_event",
     *   operationId="MetadataEvent::all",
     *   tags={"MetadataEvent"},
     *   x={"owner"={
     *     "$ref"="#/components/schemas/MetadataEvent"}
     *   },
     *   summary="Get the set of all metadata events.",
     *   description="Get the set of all metadata events.",
     *   @OA\Response(response=200, ref="#/components/responses/Success"),
     *   @OA\Response(response=403, ref="#/components/responses/Forbidden"),
     *   @OA\Response(response=404, ref="#/components/responses/NotFound"),
     *   @OA\Response(response=500, ref="#/components/responses/ServerFault"),
     *   security={{"Authorization": {}}},
     * )
     */
    public static function all() {
        self::authorize(function($type, $value) {
            return true;
        });
        return null;
    }
}
