version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/repo/dashboard
    docker:
      - image: rdfriedl/circleci-node-aws
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: 
          name: Install dependencies...
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Deploy to AWS S3...
          command: npm run build && npm run deploy
