<?php
require_once __DIR__ . '/LAMP.php';
require_once __DIR__ . '/driver/FitnessEventDriver.php';

/**
 * @OA\Schema(
 *   type="string",
 *   enum={"height", "weight", "heart_rate", "blood_pressure", "respiratory_rate", "sleep", "steps", "flights"},
 *   description="The kind of fitness event produced."
 * )
 */
abstract class FitnessSampleType extends LAMP {
    const Height = "height";
    const Weight = "weight";
    const HeartRate = "heart_rate";
    const BloodPressure = "blood_pressure";
    const RespiratoryRate = "respiratory_rate";
    const Sleep = "sleep";
    const Steps = "steps";
    const Flights = "flights";
}

/**
 * @OA\Schema(
 *   description="A fitness sub-sample within an event."
 * )
 */
class FitnessSample extends LAMP {

    /** 
     * @OA\Property(
     *   ref="#/components/schemas/FitnessSampleType",
     *   description="The type of fitness sample."
     * )
     */
    public $type = null;

    /** 
     * @OA\Property(
     *   type="string",
     *   description="The units used in the value of the sample."
     * )
     */
    public $unit = null;

    /** 
     * @OA\Property(
     *   description="The numeric or string value of the sample."
     * )
     */
    public $value = null;
}

/**
 * @OA\Schema(
 *   description="An event generated by a participant's device, linked fitness trackers, or wearable devices."
 * )
 */
class FitnessEvent extends LAMP {
    use FitnessEventDriver;
    
    /**
     * @OA\Property(
     *   ref="#/components/schemas/Identifier",
     *   x={"type"="#/components/schemas/FitnessEvent"},
     *   description="The self-referencing identifier to this object."
     * )
     */
    public $id = "";

    /** 
     * @OA\Property(
     *   ref="#/components/schemas/Attachments",
     *   description="External or out-of-line objects attached to this object."
     * )
     */
    public $attachments = null;

    /** 
     * @OA\Property(
     *   ref="#/components/schemas/Timestamp",
     *   description="The date and time when this event was recorded."
     * )
     */
    public $timestamp = null;

    /** 
     * @OA\Property(
     *   type="array",
     *   @OA\Items(
     *     ref="#/components/schemas/FitnessSample"
     *   ),
     *   description="The set of all sub-samples within the event."
     * )
     */
    public $record = null;

    /** 
     * @OA\Get(
     *   path="/fitness_event/{fitness_event_id}",
     *   operationId="FitnessEvent::view",
     *   tags={"FitnessEvent"},
     *   x={"owner"={
     *     "$ref"="#/components/schemas/FitnessEvent"}
     *   },
     *   summary="Get a single fitness event, by identifier.",
     *   description="Get a single fitness event, by identifier.",
     *   @OA\Parameter(
     *     name="fitness_event_id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(
     *       ref="#/components/schemas/Identifier",
     *       x={"type"={
     *         "$ref"="#/components/schemas/FitnessEvent"}
     *       },
     *     )
     *   ),
     *   @OA\Parameter(ref="#/components/parameters/Export"),
     *   @OA\Parameter(ref="#/components/parameters/XPath"),
     *   @OA\Response(response=200, ref="#/components/responses/Success"),
     *   @OA\Response(response=403, ref="#/components/responses/Forbidden"),
     *   @OA\Response(response=404, ref="#/components/responses/NotFound"),
     *   @OA\Response(response=500, ref="#/components/responses/ServerFault"),
     *   security={{"AuthorizationLegacy": {}}},
     * )
     */
    public static function view($fitness_event_id) {
        $_id = (new TypeID($fitness_event_id))->require([FitnessEvent::class]);
        self::authorize(function($type, $value) {
            $_id1 = self::parent_of($fitness_event_id, FitnessEvent::class, 
                        $type == AuthType::Researcher ? Researcher::class : Participant::class);
            return $value == ($type == AuthType::Researcher ? $_id1->part(1) : $_id1);
        });
        return FitnessEvent::_select(null, null, $_id->part(1));
    }

    /** 
     * @OA\Get(
     *   path="/participant/{participant_id}/fitness_event",
     *   operationId="FitnessEvent::all_by_participant",
     *   tags={"FitnessEvent"},
     *   x={"owner"={
     *     "$ref"="#/components/schemas/FitnessEvent"}
     *   },
     *   summary="Get the set of all fitness events produced by a participant, by identifier.",
     *   description="Get the set of all fitness events produced by a participant, by identifier.",
     *   @OA\Parameter(
     *     name="participant_id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(
     *       ref="#/components/schemas/Identifier",
     *       x={"type"={
     *         "$ref"="#/components/schemas/Participant"}
     *       },
     *     )
     *   ),
     *   @OA\Parameter(ref="#/components/parameters/Export"),
     *   @OA\Parameter(ref="#/components/parameters/XPath"),
     *   @OA\Response(response=200, ref="#/components/responses/Success"),
     *   @OA\Response(response=403, ref="#/components/responses/Forbidden"),
     *   @OA\Response(response=404, ref="#/components/responses/NotFound"),
     *   @OA\Response(response=500, ref="#/components/responses/ServerFault"),
     *   security={{"AuthorizationLegacy": {}}},
     * )
     */
    public static function all_by_participant($participant_id) {
        self::authorize(function($type, $value) use($participant_id) {
            if ($type == AuthType::Researcher) {
                $_id = self::parent_of($participant_id, Participant::class, Researcher::class);
                return $value == $_id->part(1);
            } else if ($type == AuthType::Participant) {
                return $value == $participant_id;
            } else return false;
        });
        return FitnessEvent::_select($participant_id);
    }

    /** 
     * @OA\Get(
     *   path="/study/{study_id}/fitness_event",
     *   operationId="FitnessEvent::all_by_study",
     *   tags={"FitnessEvent"},
     *   x={"owner"={
     *     "$ref"="#/components/schemas/FitnessEvent"}
     *   },
     *   summary="Get the set of all fitness events produced by participants enrolled in a study, by identifier.",
     *   description="Get the set of all fitness events produced by participants enrolled in a study, by identifier.",
     *   @OA\Parameter(
     *     name="study_id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(
     *       ref="#/components/schemas/Identifier",
     *       x={"type"={
     *         "$ref"="#/components/schemas/Study"}
     *       },
     *     )
     *   ),
     *   @OA\Parameter(ref="#/components/parameters/Export"),
     *   @OA\Parameter(ref="#/components/parameters/XPath"),
     *   @OA\Response(response=200, ref="#/components/responses/Success"),
     *   @OA\Response(response=403, ref="#/components/responses/Forbidden"),
     *   @OA\Response(response=404, ref="#/components/responses/NotFound"),
     *   @OA\Response(response=500, ref="#/components/responses/ServerFault"),
     *   security={{"AuthorizationLegacy": {}}},
     * )
     */
    public static function all_by_study($study_id) {
        return FitnessEvent::all_by_researcher($study_id);
    }

    /** 
     * @OA\Get(
     *   path="/researcher/{researcher_id}/fitness_event",
     *   operationId="FitnessEvent::all_by_researcher",
     *   tags={"FitnessEvent"},
     *   x={"owner"={
     *     "$ref"="#/components/schemas/FitnessEvent"}
     *   },
     *   summary="Get the set of all fitness events produced by participants enrolled in any study conducted by a researcher, by identifier.",
     *   description="Get the set of all fitness events produced by participants enrolled in any study conducted by a researcher, by identifier.",
     *   @OA\Parameter(
     *     name="researcher_id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(
     *       ref="#/components/schemas/Identifier",
     *       x={"type"={
     *         "$ref"="#/components/schemas/Researcher"}
     *       },
     *     )
     *   ),
     *   @OA\Parameter(ref="#/components/parameters/Export"),
     *   @OA\Parameter(ref="#/components/parameters/XPath"),
     *   @OA\Response(response=200, ref="#/components/responses/Success"),
     *   @OA\Response(response=403, ref="#/components/responses/Forbidden"),
     *   @OA\Response(response=404, ref="#/components/responses/NotFound"),
     *   @OA\Response(response=500, ref="#/components/responses/ServerFault"),
     *   security={{"AuthorizationLegacy": {}}},
     * )
     */
    public static function all_by_researcher($researcher_id) {
        $_id = (new TypeID($researcher_id))->require([Researcher::class, Study::class]);
        self::authorize(function($type, $value) use($_id) {
            return ($type == AuthType::Researcher && $value == $_id->part(1));
        });
        return FitnessEvent::_select(null, $_id->part(1));
    }

    /** 
     * @OA\Get(
     *   path="/fitness_event",
     *   operationId="FitnessEvent::all",
     *   tags={"FitnessEvent"},
     *   x={"owner"={
     *     "$ref"="#/components/schemas/FitnessEvent"}
     *   },
     *   summary="Get the set of all fitness events.",
     *   description="Get the set of all fitness events.",
     *   @OA\Parameter(ref="#/components/parameters/Export"),
     *   @OA\Parameter(ref="#/components/parameters/XPath"),
     *   @OA\Response(response=200, ref="#/components/responses/Success"),
     *   @OA\Response(response=403, ref="#/components/responses/Forbidden"),
     *   @OA\Response(response=404, ref="#/components/responses/NotFound"),
     *   @OA\Response(response=500, ref="#/components/responses/ServerFault"),
     *   security={{"AuthorizationLegacy": {}}},
     * )
     */
    public static function all() {
        self::authorize(function($type, $value) {
            return false;
        });
        return FitnessEvent::_select();
    }
}
