name: "Deploy ECS"
on:
  workflow_call:
    inputs:
      env:
        description: Target environment of deployment. (stg, prod)
        required: true
        type: string
      container_tag:
        description: 'The container tag to deploy'
        required: true
        type: string

permissions:
  contents: 'read'
  id-token: 'write'

concurrency:
  group: ${{ inputs.env }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}
          aws-region: us-east-2

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ vars.ECS_TASK_DEF_FAMILY }} \
            --query taskDefinition \
            > task-definition.json
          cat task-definition.json
          which jq

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-definition.json
          service: ${{ vars.ECS_SERVICE }}
          cluster: ${{ vars.ECS_CLUSTER }}
          wait-for-service-stability: true