name: 'Manual Deploy'
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: The container tag to deploy
      env:
        type: environment
        default: stg

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  # todo: find digest
  deploy:
    name: "Deploy"
    uses: ./.github/workflows/callable-deploy-ecs.yml
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      container_digest: ${{ inputs.tag }}