name: 'Manually deploy tag'
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: The tag to deploy (must already exist)
      env:
        type: environment
        default: stg

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  deploy-env-stg:
    name: "Deploy to stg environment"
    uses: ./.github/workflows/callable-deploy-ecs.yml
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      container_tag: ${{ inputs.tag }}