name: On Merge or Push (to master)
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  build-docker:
    name: "Build & Push Docker Image"
    uses: ./.github/workflows/callable-build-docker.yml
    secrets: inherit
    with:
      push: true

  deploy-env-stg:
    name: "Deploy in Staging"
    uses: ./.github/workflows/callable-deploy-ecs.yml
    secrets: inherit
    with:
      env: stg
      container_tag: master
    needs: 
      - build-docker