name: On tag
on:
  push:
    tags: '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  build-docker:
    name: "Build Container"
    uses: ./.github/workflows/callable-build-docker.yml
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      push: true
    needs:
      - pre-run

  deploy-stg:
    name: "Deploy to stg environment"
    uses: ./.github/workflows/callable-deploy-ecs.yml
    secrets: inherit
    with:
      env: stg
      container_tag: ${{ github.ref }}
    needs: 
      - build-docker

  deploy-pages:
    name: "Publish gh-pages"
    uses: ./.github/workflows/callable-deploy-ghpages.yml
    secrets: inherit
    needs: 
      - deploy-stg