name: Tag Pushed
on:
  push:
    tags: '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-docker:
    name: "Build Container"
    uses: ./.github/workflows/callable-build-docker.yml
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      push: true

  deploy-stg:
    name: "Deploy to stg environment"
    uses: ./.github/workflows/callable-deploy-ecs.yml
    secrets: inherit
    with:
      env: stg
      container_tag: ${{ github.ref }}
    needs: 
      - build-docker
