name: Production Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Image Build
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bidmcdigitalpsychiatry/lamp-dashboard/app
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
